### PR TITLE
fix the plist_options warning

### LINKED ISSUE #6: Deprecated API
Hi, there's a warning about deprecated api, would you fix it? thanks.

```ruby
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the cmacrae/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cmacrae/homebrew-formulae/spacebar.rb:33
```

### PR DESCRIPTION
**Pull request by lazywalker**
fix #6 it seems ok now :)

### CODE REVIEW

**Review by Therzok — APPROVED** [review]

**Comment by Therzok** [comment]
@cmacrae can you PTAL?

**Comment by JuliusDegesys** [comment]
FWIW, this fix works for me

**Comment by aserranoni** [comment]
Also works for me!

**Comment by tinyCatzilla** [comment]
Working for me as well. @cmacrae PTAL, important fix for installation

**Comment by cmacrae** [comment]
thanks for this @lazywalker! and thanks for everyone's patience on this PR - I've just merged it :)

**Comment by tinyCatzilla** [comment]
Thanks! Just tested a fresh install this morning and is working as intended. I believe this can be closed now.

**Pull request merged**
